name: Dependabot Labeler
on:
  pull_request:
    types:
      - opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_URL: ${{github.event.pull_request.html_url}}
  # Labels
  LABEL_DEVELOPMENT: "dependencies:development"
  LABEL_PRODUCTION: "dependencies:production"
  LABEL_SEMVER_DEFAULT: "semver:patch"

permissions:
  pull-requests: write

jobs:
  dependabot-labeler:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Metadata
        run: |
          echo ${{ steps.metadata.outputs.package-ecosystem }}
          echo ${{ steps.metadata.outputs.dependency-type }}

      # Semver Label
      - name: Add semver:patch label
        id: label-semver-patch
        run: gh pr edit "${{env.PR_URL}}" --add-label "${{env.LABEL_SEMVER_DEFAULT}}"

      # Python Dependencies
      - name: Python Production
        id: label-python-production
        if: steps.metadata.outputs.package-ecosystem == 'pip' && startsWith(github.head_ref, 'dependabot/pip/development-dependencies') == false
        run: gh pr edit "${{env.PR_URL}}" --add-label "${{env.LABEL_PRODUCTION}}"

      - name: Python Development
        id: label-python-development
        if: steps.metadata.outputs.package-ecosystem == 'pip' && startsWith(github.head_ref, 'dependabot/pip/development-dependencies')
        run: gh pr edit "${{env.PR_URL}}" --add-label "${{env.LABEL_DEVELOPMENT}}"

      # GitHub Actions Dependencies
      - name: GitHub Actions
        id: label-github-actions
        if: steps.metadata.outputs.package-ecosystem == 'github-actions'
        run: gh pr edit "${{env.PR_URL}}" --add-label "${{env.LABEL_DEVELOPMENT}}"
